CREATE TABLE video_asr_chunk (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  processing_task_id BIGINT NOT NULL,
  task_record_id BIGINT NOT NULL,
  video_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  chunk_index INT NOT NULL,
  extraction_start_ms BIGINT NOT NULL,
  extraction_end_ms BIGINT NOT NULL,
  logical_start_ms BIGINT NOT NULL,
  logical_end_ms BIGINT NOT NULL,
  audio_sha256 CHAR(64) NULL,
  engine_signature CHAR(64) NOT NULL,
  state VARCHAR(32) NOT NULL DEFAULT 'PLANNED',
  provider_task_id VARCHAR(32) NULL,
  submit_attempt INT NOT NULL DEFAULT 0,
  result_json JSON NULL,
  error_code VARCHAR(128) NULL,
  error_message VARCHAR(2048) NULL,
  submitted_time DATETIME NULL,
  completed_time DATETIME NULL,
  created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_video_asr_chunk_task_order (processing_task_id, chunk_index),
  KEY idx_video_asr_chunk_video (video_id, processing_task_id),
  KEY idx_video_asr_chunk_state (state, updated_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
